# bcftools. tests/bin/bcftools is a stand-in that lists the sequences chr1 and
# chr2 and the samples sampleA and sampleB.
__luish_internal plugin load "$EXTRA/complete/bio"
echo "load $?"
c() {
    echo "--- $1"
    __luish_internal complete "$1"
}
mkdir -p data
touch data/calls.vcf.gz data/calls.vcf.gz.tbi data/calls.bcf data/notes.txt data/genome.fa data/regions.bed data/a.bam data/list.txt
echo "=== bcftools"
c 'bcftools '
c 'bcftools vie'
c 'bcftools view -'
c 'bcftools view --'
c 'bcftools view -O '
c 'bcftools view --output-type='
c 'bcftools view --regions-overlap '
c 'bcftools view -v '
c 'bcftools view data/'
c 'bcftools view data/calls.vcf.gz '
c 'bcftools view -r '
c 'bcftools view data/calls.bcf -r c'
c 'bcftools view -s '
c 'bcftools view data/calls.vcf.gz -s s'
c 'bcftools view -R data/'
c 'bcftools view -o out.vcf data/'
c 'bcftools view -W'
c 'bcftools view --write-index='
echo "=== other subcommands"
c 'bcftools index -'
c 'bcftools index data/'
c 'bcftools annotate -a data/'
c 'bcftools annotate --pair-logic '
c 'bcftools concat -d '
c 'bcftools concat -'
c 'bcftools isec -c '
c 'bcftools isec -p data/'
c 'bcftools merge -m '
c 'bcftools merge -F '
c 'bcftools norm -f data/'
c 'bcftools norm -c '
c 'bcftools norm -m '
c 'bcftools norm -S '
c 'bcftools query -f '
c 'bcftools query -v data/'
c 'bcftools query -l data/calls.vcf.gz'
c 'bcftools call --ploidy '
c 'bcftools call -V '
c 'bcftools call -C '
c 'bcftools consensus -f data/'
c 'bcftools consensus -H '
c 'bcftools consensus -m data/'
c 'bcftools csq -p '
c 'bcftools csq -O '
c 'bcftools filter -S '
c 'bcftools filter -m '
c 'bcftools gtcheck -g data/'
c 'bcftools mpileup -f data/'
c 'bcftools mpileup -X '
c 'bcftools mpileup data/'
c 'bcftools mpileup --ar '
c 'bcftools plugin '
c 'bcftools plugin fill'
c 'bcftools plugin fill-tags data/'
c 'bcftools roh -O '
c 'bcftools stats -c '
c 'bcftools stats -F data/'
c 'bcftools reheader -h data/'
c 'bcftools sort -T '
c 'bcftools head -'
c 'bcftools nosuchsub -'
